SELECT *
FROM CDO_Q_DOCUMENTO
WHERE CONCAT(DOCUMENTO, CONCAT(' - ', ANIO)) IN (

    SELECT CONCAT(CONCAT(DOC.DOCUMENTO, ' - '), DOC.ANIO) AS DOCUMENTO
    FROM CDO_DOCUMENTO DOC
    INNER JOIN CDO_DETDOCUMENTO DET
    ON DOC.DOCUMENTO = DET.DOCUMENTO
    AND DOC.ANIO = DET.ANIO
    AND DOC.CODIGOCLASE = DET.CODIGOCLASE
    AND DOC.CODIGOCLASE = 3
    AND DET.CODTRAMITE = 192
    AND DOC.FECHA_ISO IS NOT NULL
    AND TO_CHAR(DOC.FECHA, 'MM/YYYY') = '09/2019'
    
);

SELECT CONCAT(CONCAT(DOC.DOCUMENTO, ' - '), DOC.ANIO) AS DOCUMENTO, DOC.DOCUMENTO AS DOCUMENTO_, DOC.ANIO AS ANIO_,
DOC.PRIMER_NOMBRE, DOC.FOLIOS, DOC.DIR_NOTIFICA, DOC.TELEFONO,
DOC.PRIMER_APELLIDO, TO_CHAR(DOC.FECHA, 'DD/MM/YYYY') AS FECHA, DOC.USUARIO, DOC.PLAZO_HORAS, NVL(DOC.CALIDAD, 0) AS CALIDAD
FROM CDO_DOCUMENTO DOC
INNER JOIN CDO_DETDOCUMENTO DET
ON DOC.DOCUMENTO = DET.DOCUMENTO
AND DOC.ANIO = DET.ANIO
AND DOC.CODIGOCLASE = DET.CODIGOCLASE
AND DOC.CODIGOCLASE = 3
AND DET.CODTRAMITE = 192
AND DOC.FECHA_ISO IS NOT NULL
AND DOC.CALIDAD IS NULL
ORDER BY DOC.DOCUMENTO DESC;

SELECT CONCAT(CONCAT(DOC.DOCUMENTO, ' - '), DOC.ANIO) AS DOCUMENTO, DOC.PRIMER_NOMBRE,
DOC.PRIMER_APELLIDO, TO_CHAR(DOC.FECHA, 'DD/MM/YYYY') AS FECHA, DOC.USUARIO, DOC.PLAZO_HORAS, NVL(DOC.CALIDAD, 0) AS CALIDAD
FROM CDO_DOCUMENTO DOC
INNER JOIN CDO_DETDOCUMENTO DET
ON DOC.DOCUMENTO = DET.DOCUMENTO
AND DOC.ANIO = DET.ANIO
AND DOC.CODIGOCLASE = DET.CODIGOCLASE
AND DOC.CODIGOCLASE = 3
AND DET.CODTRAMITE = 192
AND DOC.FECHA_ISO IS NOT NULL
AND TO_CHAR(DOC.FECHA, 'MM/YYYY') = '09/2019'
ORDER BY DOC.DOCUMENTO DESC;

